[global]
fps = 60
duration = 1.2
vsync = true
easing = "expo"
shift_percent = 5
shift = 1000

[global.parallax.invert.cursor]
x = false
y = true

[global.input.cursor]
follow_global = true
sensitivity_x = 1.2
sensitivity_y = 0.8
deadzone_px = 5
ema_alpha = 0.3        # Smooth cursor movement
animation_duration = 2.0
easing = "expo"

[global.parallax]
input = "workspace"
# input = "workspace,cursor"

# [global.parallax.max_offset_px]
# x = 300
# y = 1000

[[global.layers]]
path = "/mnt/Rikai/Files/Wallpaper/Parallax/game_background_3/layers/sky.png"
scale = 1.3
shift_multipier = 50
align = { x = "center", y = "top" }
fit = "cover"
# uv_offset = { x = 0, y = 0 }

# [[global.layers]]
# path = "/mnt/Rikai/Files/Wallpaper/Parallax/game_background_3/layers/rocks.png"
# scale = 2
# shift_multipier = 5

# [[global.layers]]
# path = "/mnt/Rikai/Files/Wallpaper/Parallax/game_background_3/layers/clouds_1.png"
# scale = 2
# shift_multipier = 5


# [[global.layers]]
# path = "/mnt/Rikai/Files/Wallpaper/Parallax/game_background_3/layers/rocks.png"
# scale = 2
# shift_multipier = 5

# [[global.layers]]
# path = "/mnt/Rikai/Files/Wallpaper/Parallax/game_background_3/layers/sky.png"

# [[global.layers]]
# path = "/mnt/Rikai/Files/Wallpaper/Parallax/game_background_3/layers/sky.png"
